name: Rollback Firebase Hosting
on:
  workflow_dispatch:
    inputs:
      version:
        description: 'Version to rollback to (leave empty for previous version)'
        required: false
        default: ''

jobs:
  rollback:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      
      - name: Rollback Firebase Hosting
        uses: w9jds/firebase-action@v12.4.0
        with:
          args: hosting:clone ${{ inputs.version != '' && format('fezz-452821:{0}', inputs.version) || 'fezz-452821:live^1' }} fezz-452821:live
        env:
          GCP_SA_KEY: ${{ secrets.FIREBASE_SERVICE_ACCOUNT }}
          
      - name: Notify Success
        run: echo "Rollback completed successfully!"