name: Rollback Firebase Hosting
on:
  workflow_dispatch:
    inputs:
      version:
        description: 'Version to rollback to (leave empty for previous version)'
        required: false
        default: ''

jobs:
  rollback:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      id-token: write
    steps:
      - uses: actions/checkout@v3
      
      - name: Write Service Account
        run: echo '${{ secrets.FIREBASE_SERVICE_ACCOUNT }}' > service-account.json
        
      - name: Install Firebase CLI
        run: npm install -g firebase-tools
      
      - name: Rollback to Specific Version
        if: inputs.version != ''
        run: |
          export GOOGLE_APPLICATION_CREDENTIALS="$PWD/service-account.json"
          firebase hosting:clone fezz-452821:${{ inputs.version }} fezz-452821:live --project fezz-452821
        
      - name: Rollback to Previous Version
        if: inputs.version == ''
        run: |
          export GOOGLE_APPLICATION_CREDENTIALS="$PWD/service-account.json"
          firebase hosting:clone fezz-452821:live^1 fezz-452821:live --project fezz-452821
          
      - name: Notify Success
        run: echo "Rollback completed successfully!"