name: Rollback Firebase Hosting
on:
  workflow_dispatch:
    inputs:
      version:
        description: 'Version to rollback to (leave empty for previous version)'
        required: false
        default: ''

jobs:
  rollback:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      
      - name: Rollback Firebase Hosting
        uses: FirebaseExtended/action-hosting-deploy@v0
        with:
          repoToken: '${{ secrets.GITHUB_TOKEN }}'
          firebaseServiceAccount: '${{ secrets.GCP_SA_KEY }}'
          projectId: fezz-452821
          channelId: live
          expires: 30d
          entryPoint: "."
          target: ${{ inputs.version != '' && inputs.version || 'live^1' }}
          
      - name: Notify Success
        run: echo "Rollback completed successfully!"